api:
  main:
    root: ./openapi/openapi.yaml
lint:
  extends:
    - recommended
  rules:
    no-unused-components: warning
    no-ambiguous-paths: off
features.openapi:
  htmlTemplate: ./docs/index.html
  showConsole: true
